baseURL = "https://helenamm.com"
languageCode = "en-us"
title = "HELENA MARTINEZ MERINO"
theme = "hugo-creative-portfolio-theme"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "red"
  description = "Helena Martinez Merino Portfolio"
  copyright = "2017 Helena M.M."
  subdescription = "UX/UI Designer & Front-end Developer"
  sidebarAbout = [
    "Design Thinking • Agile & Lean UX • Sketch",
    "HTML5 & CSS • Javascript • React JS • Node JS"
  ]
  email = "helena.mrtz@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Work"
  url = ""

  [[params.navlinks]]
  name = "About me"
  url = "/about/"

  [[params.navlinks]]
  name = "Contact"
  url = "/contact/"

  [params.social]
  email         = "helena.mrtz@gmail.com"
  twitter       = "https://twitter.com/helenammerino"
  linkedin      = "https://www.linkedin.com/in/helena-martinez-merino/"
  github        = "https://github.com/helenamm"
  medium        = "https://medium.com/@helenamm"
  # googleplus    = "full profile url in googleplus"
  # facebook      = "full page or profile url in facebook"
  # instagram     = "full profile url in instagram"
  # stackoverflow = "full profile url in stackoverflow"
