baseURL = "https://helenamm.com"
languageCode = "en-us"
title = "HELENA MARTINEZ MERINO"
theme = "hugo-creative-portfolio-theme"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Helena Martinez Merino Portfolio"
  copyright = "&copy;2017 Helena M.M."
  sidebarAbout = [
    "Arquitecta técnica reciclada en front-end developer.",
    "Actual UX/UI ironhacker."
  ]
  email = "helena.mrtz@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Trabajos"
  url = ""

  [[params.navlinks]]
  name = "Sobre mí"
  url = "/about/"

  [[params.navlinks]]
  name = "Contacto"
  url = "/contact/"

  [params.social]
  email         = "helena.mrtz@gmail.com"
  twitter       = "https://twitter.com/helenammerino"
  linkedin      = "https://www.linkedin.com/in/helena-martinez-merino/"
  github        = "https://github.com/helenamm"
  medium        = "https://medium.com/@helenamm"
  # googleplus    = "full profile url in googleplus"
  # facebook      = "full page or profile url in facebook"
  # instagram     = "full profile url in instagram"
  # stackoverflow = "full profile url in stackoverflow"
